// Declarative Pipeline where we define the steps to be executed directly into the pipeline unlike Scripted where we for each stage
// we have groovy script running in background which can be more flexible and less tedious.
pipeline{

    agent any

    stages{
        stage('Checkout'){
            steps
            {
                echo 'Checkout code from github Repository'
            }
        }

        stage('Build'){
            steps
            {
                echo 'Build the code'
            }
        }

        stage('Test'){
            steps
            {
                echo 'Test the code'
            }
        }

        stage('Deploy'){
            steps
            {
                echo 'Deploy the code'
            }
        }
    }
}